### ISSUE TITLE
Cannot use SITE var when using a zeo setup

### ISSUE THREAD

**Issue by pnicolli** [plone/plone.docker#135]
This is a sample docker-compose config file:

```yaml
version: '3.7'

services:
  zeo:
    image: plone:5.2.1
    command: zeo
  client:
    image: plone:5.2.1
    depends_on:
      - zeo
    environment:
      - ZEO_ADDRESS=zeo:8080
      - SITE=intranet
    ports:
      - '8080:8080'
```

The launch of the client instance will fail like this:

```
ValueError: Directory layout `zeocache` selected for blob directory /data/blobstorage/, but marker found for layout `bushy`
```

After some investigation, we found out this happens because ``collective.recipe.plonesite`` needs to be configured with the ``zeoserver`` option: https://pypi.org/project/collective.recipe.plonesite/#options

Afaik, there is no way to configure that right now. Is this correct?
