### ISSUE TITLE
Update docker-compose example to v2

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#20]
With the latest release of docker-compose there is also a new syntax released

Example:

```
version: '2'
services:
  web:
    build: .
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
```

more info: https://docs.docker.com/compose/compose-file/
