### ISSUE TITLE
Double check docs, confusing info about zeoserver

### ISSUE THREAD

**Issue by svx** [plone/plone.docker#51]
@avoinea 

Currently we have:

```
haproxy:
  image: eeacms/haproxy
  ports:
  - 8080:5000
  - 1936:1936
  links:
  - plone
  environment:
  - BACKENDS_PORT=8080
  - SERVICE_NAMES=plone

plone:
  image: plone
  links:
  - zeoserver
  environment:
  - ZEO_ADDRESS=zeoserver:8100

zeoserver:
  image: plone
  command: zeoserver
```

Does that mean, we do not use the plone/zeoserver image and iinstead we use our 'normal' plone/plone image ?

We have the same here:

```
ZEO Cluster

Start ZEO server

docker run --name=zeo plone zeoserver

```

Should that be

```
docker run --name=zeo plone/zeoserver
```
?
