### ISSUE TITLE
ZEO listens to localhost:8080 only? (in 4.3.17)

### ISSUE THREAD

**Issue by jensens** [plone/plone.docker#99]
This 
https://github.com/plone/plone.docker/blob/af1b89b8c2a0c89b91dac590386b9de4e4f9946f/4.3/4.3.17/debian/buildout.cfg#L21
with `docker-compose.yml` like this:
```
  [...]
  zeoserver:
    image: plone:4.3
    command: zeoserver
    volumes:
    - data:/data
    restart: always
  [...]
```
results in:
```
zeoserver_1     | Application running on pid=26
zeoserver_1     | 2018-05-23T07:25:32 (26) listening on ('127.0.0.1', 8100)
```
Which then blocks plone to connect to the exposed port (because expose seems to need to be bound to the external interface too).

**Comment by jensens** [comment]
Also, don't we need an ``EXPOSE=8100`` as well here:
https://github.com/plone/plone.docker/blob/af1b89b8c2a0c89b91dac590386b9de4e4f9946f/4.3/4.3.17/debian/Dockerfile#L51

**Comment by avoinea** [comment]
@jensens The new command is `zeo` and port `8080` like:
```
  [...]
  zeoserver:
    image: plone:4.3
    command: zeo
    volumes:
    - data:/data
    restart: always
  [...]
```

`zeoserver` is there for backward compatibility, but it seems it's not backward compatible anymore.
